{
  imports = [
    ./ddns.nix
    ./development.nix
    ./display.nix
    ./fail2ban.nix
    ./fonts.nix
    ./gaming.nix
    ./graphical.nix
    ./host.nix
    ./hyprland.nix
    ./kernel.nix
    ./kmscon.nix
    ./libvirt.nix
    ./rpi.nix
    ./snapper.nix
    ./spicetify.nix
    ./substituters.nix
    ./sysctl.nix
    ./upnp.nix
    ./wifi.nix
    ./wireguard.nix
  ];
}
