{
  programs.htop.enable = true;

  environment.etc.htoprc.text = /* ini */ ''
    htop_version=3.5.1
    config_reader_min_version=3
    account_guest_in_cpu_meter=1
    all_branches_collapsed=0
    color_scheme=0
    cpu_count_from_one=0
    degree_fahrenheit=0
    delay=10
    detailed_cpu_time=1
    enable_mouse=1
    fields=0 53 48 49 54 17 18 38 39 40 119 50 115 132 46 47 2 1
    find_comm_in_cmdline=1
    header_layout=three_33_34_33
    header_margin=1
    hide_function_bar=2
    hide_kernel_threads=0
    hide_running_in_container=0
    hide_userland_threads=1
    highlight_base_name=1
    highlight_changes=0
    highlight_changes_delay_secs=5
    highlight_deleted_exe=1
    highlight_megabytes=1
    highlight_threads=1
    screen_tabs=1
    shadow_distribution_path_prefix=1
    shadow_other_users=0
    show_cached_memory=1
    show_cpu_frequency=1
    show_cpu_smt_labels=0
    show_cpu_temperature=1
    show_cpu_usage=1
    show_merged_command=1
    show_program_path=1
    show_thread_names=1
    sort_direction=-1
    sort_key=46
    strip_exe_from_cmdline=1
    tree_sort_direction=-1
    tree_sort_key=50
    tree_view=0
    tree_view_always_by_pid=0
    update_process_names=0
    column_meter_modes_0=1 1 1
    column_meter_modes_1=1 1 1
    column_meter_modes_2=2 2 2 2 2 2
    column_meters_0=LeftCPUs Memory DiskIORate
    column_meters_1=RightCPUs Swap NetworkIO
    column_meters_2=LoadAverage Tasks FileDescriptors Systemd SystemdUser Uptime
    screen:Main=PID ELAPSED USER TIME SCHEDULERPOLICY PRIORITY NICE M_VIRT M_RESIDENT M_SHARE M_SWAP NLWP GPU_PERCENT PERCENT_CPU_DELAY PERCENT_CPU PERCENT_MEM STATE Command
    screen:I/O=PID ELAPSED USER IO_PRIORITY IO_RATE IO_READ_RATE IO_WRITE_RATE RBYTES WBYTES CNCLWB PERCENT_IO_DELAY PERCENT_SWAP_DELAY Command
    screen:Memory=PID ELAPSED USER PERCENT_MEM OOM MINFLT MAJFLT M_TRS M_DRS M_LRS M_SHARE M_VIRT M_PSSWP M_SWAP M_PRIV M_RESIDENT M_PSS Command
    screen:Other=PID ELAPSED USER PPID PGRP SESSION SECATTR CCGROUP CONTAINER CWD TTY Command
  '';
}
