name: Build
on:
  push:
    paths:
      - '**.nix'
      - flake.lock
      - npins/sources.json
  workflow_dispatch:

jobs:
  nixos:
    strategy:
      fail-fast: false
      matrix:
        include:
          - host: moss
            attribute: toplevel
            os: ubuntu-24.04

          - host: scout
            attribute: toplevel
            os: ubuntu-24.04-arm

          - host: zenith
            attribute: kernel
            os: ubuntu-24.04

    name: NixOS (${{ matrix.host }})
    runs-on: ${{ matrix.os }}

    steps:
      - name: Remove unused files
        uses: mathio/gha-cleanup@v1
        with:
          remove-browsers: true
          verbose: true

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
        with:
          extra-conf: |
            log-lines = 500
            extra-substituters = https://cache.garnix.io
            extra-trusted-public-keys = cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=

      - name: Set up Cachix
        uses: cachix/cachix-action@v17
        with:
          name: errornobinaries
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          extraPullNames: nix-community

      - name: Clone repository
        uses: actions/checkout@v6

      - name: Build ${{ matrix.host }} (${{ matrix.attribute }})
        env:
          NIX_USER_CONF_FILES: "${{ env.NIX_USER_CONF_FILES }}:/etc/nix/nix.conf"
        run: |
          nix run github:Mic92/nix-fast-build -- \
            --no-nom \
            --skip-cached \
            --eval-workers 1 \
            -j 4 \
            --flake .#nixosConfigurations.${{ matrix.host }}.config.system.build.${{ matrix.attribute }}
